### ISSUE TITLE
Support a default handler when no 'job' attribute is found in the payload

### ISSUE THREAD

**Issue by jszobody** [kristianedlund/laravel-external-queue#1]
I have a distributed architecture where multiple non-Laravel apps will be posting queue messages for my Laravel app to consume. This package looks very helpful in making that happen!

However, you assume the presence of a `job` attribute in the payload, and then look for a corresponding handler in the config file (at `externalqueue.handlers.job`). 

How about adding a `externalqueue.handlers.default` or `externalqueue.defaultHandler` to the config file, which gets used anytime the payload doesn't contain a `job` attribute? I need to support situations where the queueing app didn't provide a `job` in the payload.

**Comment by kristianedlund** [comment]
Wow, I never expected anyone to actually use this package but me, but I am happy that you like it.

I think addind a default handler could be a good idea and I will look into it. You are also welcome to create a PR for it.

**Comment by jszobody** [comment]
We already forked the repo, added the default handler, and are working now on adding an IronMQ connector. We will hopefully be providing a PR soon. Thanks!
